services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: MONGO_URL
        value: your-mongodb-connection-url-here

  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: client
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-name.onrender.com
